import { NextResponse } from "next/server"
import { execSync } from "child_process"
import path from "path"
import { existsSync, readFileSync, statSync, readdirSync } from "fs"

export const dynamic = "force-dynamic"
export const runtime = "nodejs"

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, HEAD, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization",
}

export async function OPTIONS() {
  return new NextResponse(null, { status: 204, headers: CORS_HEADERS })
}

// Serve provider.tar.gz — generated via `tar czf - provider/` or fallback to static file
export async function GET() {
  const cwd = process.cwd()
  const providerDir = path.join(cwd, "provider")
  const staticTar = path.join(cwd, "public", "provider.tar.gz")

  // If static file exists (generated by scripts/setup-provider-docs.sh), serve it directly
  if (existsSync(staticTar)) {
    try {
      const buf = readFileSync(staticTar)
      return new NextResponse(buf as any, {
        status: 200,
        headers: {
          "Content-Type": "application/gzip",
          "Content-Disposition": 'attachment; filename="provider.tar.gz"',
          "Cache-Control": "public, s-maxage=3600, stale-while-revalidate=86400",
          "Content-Length": String(buf.length),
          "X-SeedInfer-Source": "public/provider.tar.gz",
          ...CORS_HEADERS,
        },
      })
    } catch {}
  }

  // Try dynamic tar via system tar (Linux Pi / WSL)
  if (existsSync(providerDir) && statSync(providerDir).isDirectory()) {
    try {
      // tar czf - -C <cwd> provider — produces gzipped tar to stdout
      const buf = execSync(`tar -czf - -C "${cwd}" provider 2>/dev/null`, {
        maxBuffer: 50 * 1024 * 1024,
        timeout: 10000,
      } as any) as unknown as Buffer
      if (buf && buf.length > 1000) {
        return new NextResponse(buf as any, {
          status: 200,
          headers: {
            "Content-Type": "application/gzip",
            "Content-Disposition": 'attachment; filename="provider.tar.gz"',
            "Cache-Control": "no-store, max-age=0",
            "Content-Length": String(buf.length),
            "X-SeedInfer-Source": "dynamic-tar",
            ...CORS_HEADERS,
          },
        })
      }
    } catch (e: any) {
      console.warn(`[provider-archive] tar exec failed: ${e?.message?.slice(0,300)}`)
    }

    // Fallback: generate minimal gzipped JSON listing (if tar not available, e.g., Windows without tar)
    try {
      const { gzipSync } = await import("zlib")
      const files: string[] = []
      function walk(dir: string, prefix: string) {
        const entries = readdirSync(dir, { withFileTypes: true })
        for (const ent of entries) {
          const full = path.join(dir, ent.name)
          const rel = path.join(prefix, ent.name)
          if (ent.isDirectory()) walk(full, rel)
          else files.push(rel)
        }
      }
      walk(providerDir, "provider")
      const payload = JSON.stringify({ note: "provider.tar.gz fallback (tar unavailable)", files, cwd }, null, 2)
      const gz = gzipSync(Buffer.from(payload))
      return new NextResponse(gz as any, {
        status: 200,
        headers: {
          "Content-Type": "application/gzip",
          "Content-Disposition": 'attachment; filename="provider.tar.gz"',
          "Cache-Control": "no-store, max-age=0",
          "X-SeedInfer-Source": "fallback-json-gz",
          ...CORS_HEADERS,
        },
      })
    } catch {}
  }

  return NextResponse.json(
    { error: { message: "provider.tar.gz not available", code: "not_found" } },
    { status: 404, headers: CORS_HEADERS }
  )
}

export async function HEAD() {
  return GET()
}
